import type { Metadata } from "next";
import { Chivo, Poltawski_Nowy } from "next/font/google";
import "./globals.css";

const chivo = Chivo({ subsets: ["latin"], variable: "--font-sans" });
const poltawski = Poltawski_Nowy({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chivo.className} ${poltawski.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
