import type { Metadata } from "next";

import { Rubik, Roboto_Slab, Anton_SC } from 'next/font/google'

import "./globals.css";

const sans = Rubik({
  weight: ["500", "700"],
  variable: "--font-sans",
  subsets: ["latin"]
})

const serif = Roboto_Slab({
  weight: "400",
  variable: "--font-serif",
  subsets: ["latin"]
})

const head = Anton_SC({
  weight: "400",
  variable: "--font-head",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${head.variable} ${serif.variable} ${sans.variable} antialiased`}
      >
        <div className="min-h-screen bg-cbg flex flex-col p-4 text-black font-sans">
          {children}
        </div>
      </body>
    </html>
  );
}
