import type { Metadata } from "next";
import { Chivo, Dela_Gothic_One } from "next/font/google";
import "./globals.css";

const ChivoFont = Chivo({
  variable: "--font-chivo",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const DelaFont = Dela_Gothic_One({
  variable: "--font-dela",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ChivoFont.className} ${DelaFont.className} antialiased`}
      >
        <div className="min-h-screen bg-cyan-600 flex flex-col p-4 text-black font-[Chivo]">
          {children}
        </div>
      </body>
    </html>
  );
}
